apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kubeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: giles97/shop-frontend:latest
        ports:
        - containerPort: 80
