apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: kubeshop
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      initContainers:
      - name: init-db
        image: postgres:13
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        command: ['sh', '-c']
        args:
          - >
            until pg_isready -h localhost -U postgres;
            do echo waiting for db; sleep 2; done;
            psql -U postgres -h localhost -c "SELECT 1 FROM pg_database WHERE datname = 'kubeshop'" | grep -q 1
            || psql -U postgres -h localhost -c "CREATE DATABASE kubeshop";
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-storage
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-pvc
